# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20160518_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile1',
        ),
        migrations.AlterModelTable(
            name='profile1',
            table='profile1',
        ),
    ]
