# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20160518_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2016, 5, 18, 15, 43, 40, 578855, tzinfo=utc), upload_to=b'/home/harsh/Desktop/Registration/register'),
            preserve_default=False,
        ),
    ]
