# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_profile1_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile1',
            name='picture',
        ),
    ]
